#!/bin/bash
pwd                                                                                                                                                                                                               i     i 
